const seed = [
  {
    _id: '5ba93a6d5d907d9512e43b75',
    name: 'Bonner',
    disc: 'Velit irure quis quis adipisicing irure culpa.',
    category: 'food',
    available: false,
    instock: 4,
    price: '18.34',
    picture: 'http://placehold.it/200x200',
    brand: 'bento',
    shipping: {
      weight: '0.36',
      size: 'small',
    },
    lastUpdated: 'Wed Feb 08 2017 23:39:16 GMT+0000 (UTC)',
    tags: ['funny', 'seasonal'],
  },
  {
    _id: '5ba93a6dc34d5efd339cf01a',
    name: 'Lopez',
    disc:
      'Excepteur consequat elit velit Lorem ullamco incididunt ex aute nulla minim eu veniam.',
    category: 'food',
    available: true,
    instock: 6,
    price: '31.83',
    picture: 'http://placehold.it/200x200',
    brand: 't&K',
    shipping: {
      weight: '1.81',
      size: 'large',
    },
    lastUpdated: 'Tue Jun 12 2018 22:00:16 GMT+0000 (UTC)',
    tags: ['colorful', 'seasonal'],
  },
  {
    _id: '5ba93a6d4793654eda724f2d',
    name: 'Tran',
    disc: 'Pariatur culpa amet ex commodo.',
    category: 'food',
    available: false,
    instock: 10,
    price: '24.36',
    picture: 'http://placehold.it/200x200',
    brand: 'nike',
    shipping: {
      weight: '1.09',
      size: 'small',
    },
    lastUpdated: 'Tue Dec 29 2015 19:24:00 GMT+0000 (UTC)',
    tags: ['seasonal', 'colorful'],
  },
  {
    _id: '5ba93a6d5ee51a9a8510e54a',
    name: 'Pate',
    disc:
      'Minim nostrud incididunt deserunt commodo incididunt adipisicing est commodo officia consequat tempor sit do nostrud.',
    category: 'summer',
    available: false,
    instock: 4,
    price: '19.11',
    picture: 'http://placehold.it/200x200',
    brand: 't&K',
    shipping: {
      weight: '1.22',
      size: 'small',
    },
    lastUpdated: 'Fri Nov 11 2016 19:45:33 GMT+0000 (UTC)',
    tags: ['seasonal', 'seasonal'],
  },
  {
    _id: '5ba93a6d02db9cb39b78842c',
    name: 'Ramos',
    disc: 'Consequat ullamco veniam eiusmod eiusmod sunt in voluptate id.',
    category: 'summer',
    available: true,
    instock: 0,
    price: '14.82',
    picture: 'http://placehold.it/200x200',
    brand: 'nike',
    shipping: {
      weight: '2.8',
      size: 'small',
    },
    lastUpdated: 'Sat Jul 30 2016 23:06:27 GMT+0000 (UTC)',
    tags: ['funny', 'colorful'],
  },
  {
    _id: '5ba93a6d3fca0d9ff6f5f2c5',
    name: 'Shannon',
    disc:
      'Esse commodo mollit est veniam deserunt eiusmod consequat reprehenderit irure anim minim exercitation adipisicing.',
    category: 'christmas',
    available: true,
    instock: 6,
    price: '38.34',
    picture: 'http://placehold.it/200x200',
    brand: 'best',
    shipping: {
      weight: '1.09',
      size: 'medium',
    },
    lastUpdated: 'Fri Aug 18 2017 18:08:46 GMT+0000 (UTC)',
    tags: ['seasonal', 'funny'],
  },
  {
    _id: '5ba93a6df39ae7ca0069dbd6',
    name: 'Brock',
    disc: 'Mollit eiusmod sunt elit amet minim aliquip commodo sunt.',
    category: 'summer',
    available: false,
    instock: 0,
    price: '14.24',
    picture: 'http://placehold.it/200x200',
    brand: 'bento',
    shipping: {
      weight: '1.89',
      size: 'small',
    },
    lastUpdated: 'Tue Dec 22 2015 23:24:04 GMT+0000 (UTC)',
    tags: ['funny', 'seasonal'],
  },
  {
    _id: '5ba93a6d2744fa47b3367e6e',
    name: 'Kinney',
    disc:
      'Voluptate quis laboris elit proident elit amet tempor aute id culpa nostrud eiusmod aliqua.',
    category: 'christmas',
    available: true,
    instock: 3,
    price: '11.24',
    picture: 'http://placehold.it/200x200',
    brand: 't&K',
    shipping: {
      weight: '0.55',
      size: 'small',
    },
    lastUpdated: 'Sun Aug 27 2017 17:44:55 GMT+0000 (UTC)',
    tags: ['seasonal', 'seasonal'],
  },
  {
    _id: '5ba93a6d1c41b733380ce9fd',
    name: 'Hale',
    disc:
      'Laborum excepteur dolore duis adipisicing voluptate fugiat enim sunt.',
    category: 'christmas',
    available: false,
    instock: 1,
    price: '20.18',
    picture: 'http://placehold.it/200x200',
    brand: 't&K',
    shipping: {
      weight: '1.71',
      size: 'small',
    },
    lastUpdated: 'Thu Apr 07 2016 08:46:57 GMT+0000 (UTC)',
    tags: ['seasonal', 'colorful'],
  },
  {
    _id: '5ba93a6d21e8e90d13c4370d',
    name: 'Sellers',
    disc: 'Eiusmod tempor est exercitation ea consequat sunt fugiat.',
    category: 'summer',
    available: true,
    instock: 3,
    price: '11.48',
    picture: 'http://placehold.it/200x200',
    brand: 'best',
    shipping: {
      weight: '0.46',
      size: 'medium',
    },
    lastUpdated: 'Sun Apr 23 2017 18:08:03 GMT+0000 (UTC)',
    tags: ['colorful', 'funny'],
  },
  {
    _id: '5ba93a6dd45364213ce2c443',
    name: 'Zimmerman',
    disc:
      'Officia sit consectetur ullamco anim ad Lorem qui voluptate aute laborum.',
    category: 'christmas',
    available: true,
    instock: 10,
    price: '26.52',
    picture: 'http://placehold.it/200x200',
    brand: 't&K',
    shipping: {
      weight: '2.4',
      size: 'small',
    },
    lastUpdated: 'Fri May 08 2015 16:01:14 GMT+0000 (UTC)',
    tags: ['funny', 'seasonal'],
  },
  {
    _id: '5ba93a6df80b866e5a2ec8a4',
    name: 'Robles',
    disc:
      'Ipsum proident aute aliquip occaecat duis et officia pariatur dolor labore non anim id anim.',
    category: 'food',
    available: false,
    instock: 10,
    price: '11.84',
    picture: 'http://placehold.it/200x200',
    brand: 'nike',
    shipping: {
      weight: '1.53',
      size: 'medium',
    },
    lastUpdated: 'Tue Jun 05 2018 04:29:21 GMT+0000 (UTC)',
    tags: ['funny', 'funny'],
  },
  {
    _id: '5ba93a6de31896479176f929',
    name: 'Sosa',
    disc:
      'Ullamco labore amet enim commodo exercitation in fugiat ad nisi id reprehenderit mollit labore velit.',
    category: 'christmas',
    available: false,
    instock: 6,
    price: '38.80',
    picture: 'http://placehold.it/200x200',
    brand: 'nike',
    shipping: {
      weight: '0.2',
      size: 'large',
    },
    lastUpdated: 'Tue Nov 14 2017 01:14:36 GMT+0000 (UTC)',
    tags: ['colorful', 'funny'],
  },
  {
    _id: '5ba93a6d85ca3b78ca630e8d',
    name: 'Rosales',
    disc: 'Pariatur sint ullamco esse aliqua mollit labore sunt culpa.',
    category: 'christmas',
    available: false,
    instock: 3,
    price: '10.63',
    picture: 'http://placehold.it/200x200',
    brand: 'bento',
    shipping: {
      weight: '1.89',
      size: 'medium',
    },
    lastUpdated: 'Thu Jan 05 2017 05:05:40 GMT+0000 (UTC)',
    tags: ['funny', 'funny'],
  },
  {
    _id: '5ba93a6da49a94ab518582b8',
    name: 'Hooper',
    disc:
      'Aute ipsum officia ad sunt sunt reprehenderit pariatur est nulla minim laboris sunt.',
    category: 'christmas',
    available: false,
    instock: 3,
    price: '16.67',
    picture: 'http://placehold.it/200x200',
    brand: 'nike',
    shipping: {
      weight: '1.83',
      size: 'small',
    },
    lastUpdated: 'Mon Jan 29 2018 12:11:01 GMT+0000 (UTC)',
    tags: ['colorful', 'seasonal'],
  },
  {
    _id: '5ba93a6d3845fab1b9f4fb76',
    name: 'Russell',
    disc:
      'Laborum est dolore ipsum anim non culpa ut commodo aute amet ex mollit amet ad.',
    category: 'food',
    available: true,
    instock: 3,
    price: '17.63',
    picture: 'http://placehold.it/200x200',
    brand: 'best',
    shipping: {
      weight: '0.99',
      size: 'large',
    },
    lastUpdated: 'Tue May 01 2018 16:30:28 GMT+0000 (UTC)',
    tags: ['colorful', 'colorful'],
  },
  {
    _id: '5ba93a6ddf3d2c081e19b241',
    name: 'Madden',
    disc: 'Nulla ipsum dolore ut officia mollit quis.',
    category: 'summer',
    available: false,
    instock: 1,
    price: '25.46',
    picture: 'http://placehold.it/200x200',
    brand: 'nike',
    shipping: {
      weight: '0.53',
      size: 'large',
    },
    lastUpdated: 'Wed Apr 22 2015 20:26:52 GMT+0000 (UTC)',
    tags: ['seasonal', 'funny'],
  },
  {
    _id: '5ba93a6d1a64bf6f1fb869c6',
    name: 'Valencia',
    disc: 'Sit velit sit nostrud dolor.',
    category: 'christmas',
    available: false,
    instock: 6,
    price: '23.47',
    picture: 'http://placehold.it/200x200',
    brand: 'best',
    shipping: {
      weight: '1.53',
      size: 'small',
    },
    lastUpdated: 'Wed Jan 10 2018 05:44:38 GMT+0000 (UTC)',
    tags: ['seasonal', 'colorful'],
  },
  {
    _id: '5ba93a6df0030bff43ccdb20',
    name: 'Valentine',
    disc:
      'Amet in laborum Lorem dolore Lorem ex adipisicing non elit esse eiusmod labore.',
    category: 'christmas',
    available: false,
    instock: 6,
    price: '38.96',
    picture: 'http://placehold.it/200x200',
    brand: 'nike',
    shipping: {
      weight: '2.14',
      size: 'small',
    },
    lastUpdated: 'Tue Nov 21 2017 00:07:53 GMT+0000 (UTC)',
    tags: ['colorful', 'funny'],
  },
  {
    _id: '5ba93a6df4c0c4ebd5c3f672',
    name: 'Mcintyre',
    disc:
      'Cillum eu sit non ea eu ipsum quis duis magna eiusmod elit aliquip occaecat consequat.',
    category: 'summer',
    available: true,
    instock: 6,
    price: '26.26',
    picture: 'http://placehold.it/200x200',
    brand: 'best',
    shipping: {
      weight: 1,
      size: 'large',
    },
    lastUpdated: 'Sun Jan 17 2016 18:14:16 GMT+0000 (UTC)',
    tags: ['funny', 'colorful'],
  },
  {
    _id: '5ba93a6dde64aa57b04c2a75',
    name: 'Haley',
    disc: 'Culpa ex in est anim do cupidatat deserunt veniam officia qui.',
    category: 'summer',
    available: true,
    instock: 0,
    price: '18.07',
    picture: 'http://placehold.it/200x200',
    brand: 'nike',
    shipping: {
      weight: '1.78',
      size: 'small',
    },
    lastUpdated: 'Thu Mar 30 2017 02:20:01 GMT+0000 (UTC)',
    tags: ['seasonal', 'seasonal'],
  },
  {
    _id: '5ba93a6d88d9944bd703d065',
    name: 'Barber',
    disc:
      'Irure laboris commodo mollit occaecat labore esse irure aliquip nulla excepteur.',
    category: 'summer',
    available: true,
    instock: 4,
    price: '22.22',
    picture: 'http://placehold.it/200x200',
    brand: 'best',
    shipping: {
      weight: '2.6',
      size: 'medium',
    },
    lastUpdated: 'Thu May 04 2017 19:42:28 GMT+0000 (UTC)',
    tags: ['seasonal', 'colorful'],
  },
  {
    _id: '5ba93a6d9e5edca7ce4d66f4',
    name: 'Wynn',
    disc: 'Ea fugiat ea consequat sit voluptate consequat eiusmod quis dolore.',
    category: 'christmas',
    available: false,
    instock: 3,
    price: '35.26',
    picture: 'http://placehold.it/200x200',
    brand: 'nike',
    shipping: {
      weight: '1.16',
      size: 'large',
    },
    lastUpdated: 'Wed Nov 16 2016 04:42:39 GMT+0000 (UTC)',
    tags: ['colorful', 'funny'],
  },
  {
    _id: '5ba93a6d5657fe72b7a692b5',
    name: 'Holcomb',
    disc: 'Non aliqua eu consectetur sunt anim labore.',
    category: 'food',
    available: false,
    instock: 0,
    price: '37.38',
    picture: 'http://placehold.it/200x200',
    brand: 'best',
    shipping: {
      weight: '1.01',
      size: 'small',
    },
    lastUpdated: 'Fri Jan 12 2018 12:43:30 GMT+0000 (UTC)',
    tags: ['funny', 'funny'],
  },
  {
    _id: '5ba93a6de89d3a2aa22f82c6',
    name: 'Hutchinson',
    disc: 'Esse id esse officia adipisicing commodo ea.',
    category: 'food',
    available: true,
    instock: 4,
    price: '23.78',
    picture: 'http://placehold.it/200x200',
    brand: 'bento',
    shipping: {
      weight: '2.31',
      size: 'medium',
    },
    lastUpdated: 'Wed Jul 13 2016 10:42:32 GMT+0000 (UTC)',
    tags: ['seasonal', 'funny'],
  },
  {
    _id: '5ba93a6df7344c39d91fe997',
    name: 'Hawkins',
    disc: 'Aliqua sunt culpa elit ipsum est voluptate.',
    category: 'food',
    available: true,
    instock: 4,
    price: '19.82',
    picture: 'http://placehold.it/200x200',
    brand: 'bento',
    shipping: {
      weight: '0.99',
      size: 'large',
    },
    lastUpdated: 'Mon Jun 19 2017 07:39:30 GMT+0000 (UTC)',
    tags: ['funny', 'colorful'],
  },
  {
    _id: '5ba93a6d6f015ffc311ae2f2',
    name: 'Freeman',
    disc: 'Aliqua exercitation qui ut non voluptate.',
    category: 'summer',
    available: true,
    instock: 4,
    price: '34.45',
    picture: 'http://placehold.it/200x200',
    brand: 'bento',
    shipping: {
      weight: '2.02',
      size: 'small',
    },
    lastUpdated: 'Tue Mar 14 2017 21:19:35 GMT+0000 (UTC)',
    tags: ['seasonal', 'colorful'],
  },
  {
    _id: '5ba93a6d775e1b284dc20fc9',
    name: 'Bullock',
    disc: 'Ullamco aute ex occaecat officia laborum cupidatat.',
    category: 'food',
    available: true,
    instock: 3,
    price: '12.63',
    picture: 'http://placehold.it/200x200',
    brand: 't&K',
    shipping: {
      weight: '2.71',
      size: 'large',
    },
    lastUpdated: 'Mon May 04 2015 06:01:07 GMT+0000 (UTC)',
    tags: ['seasonal', 'seasonal'],
  },
  {
    _id: '5ba93a6df183a4729f7ffaa4',
    name: 'Todd',
    disc: 'Anim anim pariatur fugiat ipsum ex sit.',
    category: 'summer',
    available: false,
    instock: 3,
    price: '21.68',
    picture: 'http://placehold.it/200x200',
    brand: 'bento',
    shipping: {
      weight: '1.84',
      size: 'small',
    },
    lastUpdated: 'Wed Oct 12 2016 06:18:45 GMT+0000 (UTC)',
    tags: ['seasonal', 'funny'],
  },
  {
    _id: '5ba93a6da88ff3f69eabf958',
    name: 'Lamb',
    disc: 'Ullamco dolore nulla veniam irure ullamco elit.',
    category: 'food',
    available: false,
    instock: 3,
    price: '10.99',
    picture: 'http://placehold.it/200x200',
    brand: 'bento',
    shipping: {
      weight: 2,
      size: 'large',
    },
    lastUpdated: 'Thu Feb 22 2018 18:05:07 GMT+0000 (UTC)',
    tags: ['seasonal', 'seasonal'],
  },
  {
    _id: '5ba93a6dd709ad254e735328',
    name: 'Fischer',
    disc: 'Nulla magna ex dolore laborum.',
    category: 'summer',
    available: false,
    instock: 3,
    price: '28.23',
    picture: 'http://placehold.it/200x200',
    brand: 'nike',
    shipping: {
      weight: '1.84',
      size: 'medium',
    },
    lastUpdated: 'Fri Oct 07 2016 22:05:29 GMT+0000 (UTC)',
    tags: ['colorful', 'funny'],
  },
  {
    _id: '5ba93a6d167b3f24c44d31e1',
    name: 'Camacho',
    disc: 'Aute cillum id nulla deserunt ea anim.',
    category: 'food',
    available: false,
    instock: 4,
    price: '16.50',
    picture: 'http://placehold.it/200x200',
    brand: 't&K',
    shipping: {
      weight: '1.9',
      size: 'small',
    },
    lastUpdated: 'Fri May 18 2018 18:43:18 GMT+0000 (UTC)',
    tags: ['funny', 'colorful'],
  },
  {
    _id: '5ba93a6d6ec4042229476f0b',
    name: 'Barrera',
    disc:
      'Occaecat elit laborum magna proident veniam cillum ipsum labore adipisicing.',
    category: 'food',
    available: true,
    instock: 1,
    price: '18.71',
    picture: 'http://placehold.it/200x200',
    brand: 'bento',
    shipping: {
      weight: '1.04',
      size: 'small',
    },
    lastUpdated: 'Sun Jul 03 2016 20:43:00 GMT+0000 (UTC)',
    tags: ['funny', 'funny'],
  },
  {
    _id: '5ba93a6d73b71807dc51b87b',
    name: 'Cooke',
    disc: 'Ad magna dolore elit laboris cillum.',
    category: 'food',
    available: false,
    instock: 4,
    price: '22.85',
    picture: 'http://placehold.it/200x200',
    brand: 't&K',
    shipping: {
      weight: '1.26',
      size: 'medium',
    },
    lastUpdated: 'Wed Mar 21 2018 00:02:42 GMT+0000 (UTC)',
    tags: ['funny', 'funny'],
  },
  {
    _id: '5ba93a6d43314631dfeab221',
    name: 'Kemp',
    disc: 'Velit nisi commodo sit eiusmod eu reprehenderit quis.',
    category: 'christmas',
    available: true,
    instock: 10,
    price: '18.31',
    picture: 'http://placehold.it/200x200',
    brand: 't&K',
    shipping: {
      weight: '1.76',
      size: 'large',
    },
    lastUpdated: 'Fri Feb 09 2018 02:36:28 GMT+0000 (UTC)',
    tags: ['funny', 'colorful'],
  },
  {
    _id: '5ba93a6decc35f195b9e2165',
    name: 'Downs',
    disc:
      'Ea esse quis duis sint et irure nostrud culpa quis laborum labore pariatur non.',
    category: 'summer',
    available: true,
    instock: 0,
    price: '13.11',
    picture: 'http://placehold.it/200x200',
    brand: 'nike',
    shipping: {
      weight: '0.86',
      size: 'small',
    },
    lastUpdated: 'Tue Aug 29 2017 00:27:28 GMT+0000 (UTC)',
    tags: ['seasonal', 'seasonal'],
  },
  {
    _id: '5ba93a6ddfffec3d9bc91f8f',
    name: 'Meyers',
    disc: 'Quis consequat labore ut ullamco dolor excepteur in.',
    category: 'food',
    available: true,
    instock: 1,
    price: '30.90',
    picture: 'http://placehold.it/200x200',
    brand: 't&K',
    shipping: {
      weight: '2.14',
      size: 'large',
    },
    lastUpdated: 'Thu Aug 25 2016 02:15:26 GMT+0000 (UTC)',
    tags: ['seasonal', 'seasonal'],
  },
  {
    _id: '5ba93a6d26521629b67b9860',
    name: 'Silva',
    disc: 'Minim quis adipisicing sunt Lorem.',
    category: 'summer',
    available: true,
    instock: 3,
    price: '18.30',
    picture: 'http://placehold.it/200x200',
    brand: 'nike',
    shipping: {
      weight: '2.91',
      size: 'small',
    },
    lastUpdated: 'Mon Jan 23 2017 00:26:10 GMT+0000 (UTC)',
    tags: ['funny', 'colorful'],
  },
  {
    _id: '5ba93a6db0fddb49a3a49056',
    name: 'Franks',
    disc: 'Do sunt velit cillum id pariatur pariatur ipsum proident sunt ex.',
    category: 'food',
    available: false,
    instock: 3,
    price: '11.28',
    picture: 'http://placehold.it/200x200',
    brand: 't&K',
    shipping: {
      weight: '1.78',
      size: 'medium',
    },
    lastUpdated: 'Fri Jun 02 2017 03:19:00 GMT+0000 (UTC)',
    tags: ['colorful', 'seasonal'],
  },
  {
    _id: '5ba93a6dbd9b5bed3d26de04',
    name: 'Mccarthy',
    disc:
      'Aliqua veniam id nisi sit id aliqua incididunt duis veniam consectetur Lorem.',
    category: 'food',
    available: false,
    instock: 1,
    price: '26.40',
    picture: 'http://placehold.it/200x200',
    brand: 'nike',
    shipping: {
      weight: '0.44',
      size: 'large',
    },
    lastUpdated: 'Fri Nov 10 2017 17:39:03 GMT+0000 (UTC)',
    tags: ['colorful', 'funny'],
  },
  {
    _id: '5ba93a6db3cd66ae76fb6733',
    name: 'Gregory',
    disc: 'Nostrud minim sint nisi aliqua amet ipsum sint excepteur et est.',
    category: 'christmas',
    available: false,
    instock: 0,
    price: '34.30',
    picture: 'http://placehold.it/200x200',
    brand: 'bento',
    shipping: {
      weight: '1.85',
      size: 'large',
    },
    lastUpdated: 'Tue Jul 28 2015 10:13:28 GMT+0000 (UTC)',
    tags: ['seasonal', 'colorful'],
  },
  {
    _id: '5ba93a6d5a94aba7eff85f22',
    name: 'Bowers',
    disc:
      'Nulla sit nulla nostrud laborum cillum occaecat in officia aute ea eu enim magna quis.',
    category: 'summer',
    available: false,
    instock: 6,
    price: '15.37',
    picture: 'http://placehold.it/200x200',
    brand: 'nike',
    shipping: {
      weight: '2.21',
      size: 'small',
    },
    lastUpdated: 'Tue Sep 22 2015 20:36:09 GMT+0000 (UTC)',
    tags: ['colorful', 'seasonal'],
  },
  {
    _id: '5ba93a6de02f1dbb761f2b2c',
    name: 'Moss',
    disc:
      'Consectetur labore cupidatat minim occaecat exercitation non non ullamco id ea excepteur culpa exercitation.',
    category: 'food',
    available: false,
    instock: 0,
    price: '17.32',
    picture: 'http://placehold.it/200x200',
    brand: 'nike',
    shipping: {
      weight: '1.26',
      size: 'small',
    },
    lastUpdated: 'Wed Sep 28 2016 09:57:16 GMT+0000 (UTC)',
    tags: ['seasonal', 'seasonal'],
  },
  {
    _id: '5ba93a6d81b10b7ee037b87d',
    name: 'Spencer',
    disc: 'Lorem exercitation fugiat dolor Lorem.',
    category: 'summer',
    available: false,
    instock: 10,
    price: '36.97',
    picture: 'http://placehold.it/200x200',
    brand: 'nike',
    shipping: {
      weight: '2.97',
      size: 'large',
    },
    lastUpdated: 'Wed Mar 08 2017 20:05:23 GMT+0000 (UTC)',
    tags: ['funny', 'colorful'],
  },
  {
    _id: '5ba93a6ddd098bd50cfcfaef',
    name: 'Rivers',
    disc: 'Culpa enim ipsum excepteur occaecat amet nisi dolor non.',
    category: 'food',
    available: false,
    instock: 4,
    price: '26.89',
    picture: 'http://placehold.it/200x200',
    brand: 't&K',
    shipping: {
      weight: '1.95',
      size: 'small',
    },
    lastUpdated: 'Wed Mar 08 2017 13:12:49 GMT+0000 (UTC)',
    tags: ['funny', 'seasonal'],
  },
  {
    _id: '5ba93a6dc96a1fdb701f008f',
    name: 'Hunt',
    disc:
      'Exercitation adipisicing adipisicing fugiat sit minim id dolor velit nostrud nisi esse ut occaecat.',
    category: 'food',
    available: true,
    instock: 0,
    price: '25.87',
    picture: 'http://placehold.it/200x200',
    brand: 'nike',
    shipping: {
      weight: '2.95',
      size: 'large',
    },
    lastUpdated: 'Fri Apr 21 2017 08:46:59 GMT+0000 (UTC)',
    tags: ['seasonal', 'colorful'],
  },
  {
    _id: '5ba93a6d1acc6c3af4dd2a0b',
    name: 'Carson',
    disc: 'Nostrud ipsum cillum do anim laboris aliquip ipsum.',
    category: 'food',
    available: false,
    instock: 4,
    price: '37.41',
    picture: 'http://placehold.it/200x200',
    brand: 't&K',
    shipping: {
      weight: '0.36',
      size: 'large',
    },
    lastUpdated: 'Thu May 04 2017 01:27:22 GMT+0000 (UTC)',
    tags: ['colorful', 'funny'],
  },
  {
    _id: '5ba93a6d0745ca1bf0244afc',
    name: 'Livingston',
    disc: 'Fugiat exercitation ea ex nisi eiusmod.',
    category: 'christmas',
    available: true,
    instock: 3,
    price: '31.26',
    picture: 'http://placehold.it/200x200',
    brand: 'bento',
    shipping: {
      weight: '0.4',
      size: 'large',
    },
    lastUpdated: 'Sat Jun 10 2017 04:47:57 GMT+0000 (UTC)',
    tags: ['seasonal', 'seasonal'],
  },
  {
    _id: '5ba93a6d49e1ee32aa45ad41',
    name: 'Mcguire',
    disc: 'Minim consectetur amet dolore voluptate minim ullamco.',
    category: 'food',
    available: true,
    instock: 10,
    price: '29.39',
    picture: 'http://placehold.it/200x200',
    brand: 'bento',
    shipping: {
      weight: '1.95',
      size: 'large',
    },
    lastUpdated: 'Tue May 16 2017 06:22:05 GMT+0000 (UTC)',
    tags: ['funny', 'colorful'],
  },
  {
    _id: '5ba93a6da42d16016e41c48b',
    name: 'Jenkins',
    disc: 'Consectetur minim do ex anim proident et elit consequat elit.',
    category: 'summer',
    available: true,
    instock: 6,
    price: '39.64',
    picture: 'http://placehold.it/200x200',
    brand: 'bento',
    shipping: {
      weight: '0.23',
      size: 'medium',
    },
    lastUpdated: 'Thu Sep 06 2018 02:34:56 GMT+0000 (UTC)',
    tags: ['seasonal', 'colorful'],
  },
  {
    _id: '5ba93a6dc74e7555aa3e7619',
    name: 'Ramsey',
    disc:
      'Nostrud id pariatur nostrud veniam in voluptate in excepteur irure est cillum commodo ad.',
    category: 'summer',
    available: true,
    instock: 10,
    price: '11.99',
    picture: 'http://placehold.it/200x200',
    brand: 'bento',
    shipping: {
      weight: '0.29',
      size: 'small',
    },
    lastUpdated: 'Fri Jun 10 2016 05:29:14 GMT+0000 (UTC)',
    tags: ['seasonal', 'colorful'],
  },
  {
    _id: '5ba93a6da64188a319404019',
    name: 'May',
    disc:
      'Culpa ut occaecat adipisicing id mollit nostrud nostrud aliquip excepteur voluptate aliqua in.',
    category: 'summer',
    available: false,
    instock: 3,
    price: '39.10',
    picture: 'http://placehold.it/200x200',
    brand: 'best',
    shipping: {
      weight: '1.67',
      size: 'large',
    },
    lastUpdated: 'Wed Mar 21 2018 09:23:56 GMT+0000 (UTC)',
    tags: ['funny', 'funny'],
  },
  {
    _id: '5ba93a6d575a85c9bdc5481b',
    name: 'Hebert',
    disc: 'Laboris culpa sunt ut laboris ullamco ut est.',
    category: 'food',
    available: true,
    instock: 3,
    price: '16.96',
    picture: 'http://placehold.it/200x200',
    brand: 't&K',
    shipping: {
      weight: '1.54',
      size: 'small',
    },
    lastUpdated: 'Sun Mar 20 2016 19:54:13 GMT+0000 (UTC)',
    tags: ['funny', 'funny'],
  },
  {
    _id: '5ba93a6d3e15844cca1a7734',
    name: 'Ruiz',
    disc:
      'Consectetur cillum pariatur fugiat id reprehenderit commodo deserunt nulla ea nisi laboris aliquip elit.',
    category: 'summer',
    available: true,
    instock: 3,
    price: '38.72',
    picture: 'http://placehold.it/200x200',
    brand: 'best',
    shipping: {
      weight: '2.94',
      size: 'medium',
    },
    lastUpdated: 'Wed Jul 04 2018 06:42:13 GMT+0000 (UTC)',
    tags: ['colorful', 'colorful'],
  },
  {
    _id: '5ba93a6d0c8de0f5920d59d6',
    name: 'Oneill',
    disc: 'Ullamco officia mollit velit velit.',
    category: 'christmas',
    available: false,
    instock: 4,
    price: '38.22',
    picture: 'http://placehold.it/200x200',
    brand: 'bento',
    shipping: {
      weight: '1.78',
      size: 'large',
    },
    lastUpdated: 'Sun Jan 28 2018 04:29:29 GMT+0000 (UTC)',
    tags: ['funny', 'colorful'],
  },
  {
    _id: '5ba93a6da5cfc8a784cc06b9',
    name: 'Bartlett',
    disc: 'Nostrud qui pariatur officia ullamco consectetur.',
    category: 'food',
    available: false,
    instock: 6,
    price: '16.53',
    picture: 'http://placehold.it/200x200',
    brand: 'bento',
    shipping: {
      weight: '0.76',
      size: 'large',
    },
    lastUpdated: 'Sat Jan 28 2017 10:34:48 GMT+0000 (UTC)',
    tags: ['seasonal', 'funny'],
  },
  {
    _id: '5ba93a6da7b38210911b527d',
    name: 'Wilkinson',
    disc:
      'Incididunt elit pariatur exercitation est consectetur nulla deserunt non culpa anim velit velit esse.',
    category: 'food',
    available: true,
    instock: 6,
    price: '37.32',
    picture: 'http://placehold.it/200x200',
    brand: 'best',
    shipping: {
      weight: '0.8',
      size: 'large',
    },
    lastUpdated: 'Thu Apr 09 2015 16:48:40 GMT+0000 (UTC)',
    tags: ['colorful', 'colorful'],
  },
  {
    _id: '5ba93a6d93a4a80f56267bdb',
    name: 'Holmes',
    disc: 'Qui ad deserunt est duis dolor minim.',
    category: 'summer',
    available: false,
    instock: 0,
    price: '33.82',
    picture: 'http://placehold.it/200x200',
    brand: 'nike',
    shipping: {
      weight: '2.43',
      size: 'small',
    },
    lastUpdated: 'Fri Mar 02 2018 06:48:59 GMT+0000 (UTC)',
    tags: ['colorful', 'funny'],
  },
  {
    _id: '5ba93a6dc4d8a9ab6d429a37',
    name: 'Daugherty',
    disc:
      'Qui voluptate mollit adipisicing proident aliqua deserunt duis consectetur cillum.',
    category: 'food',
    available: true,
    instock: 1,
    price: '17.79',
    picture: 'http://placehold.it/200x200',
    brand: 'nike',
    shipping: {
      weight: '1.33',
      size: 'small',
    },
    lastUpdated: 'Sat Jan 13 2018 00:32:43 GMT+0000 (UTC)',
    tags: ['seasonal', 'colorful'],
  },
  {
    _id: '5ba93a6d760a1d1ed74bae01',
    name: 'Michael',
    disc: 'Veniam Lorem duis duis deserunt aliquip excepteur.',
    category: 'summer',
    available: false,
    instock: 4,
    price: '18.26',
    picture: 'http://placehold.it/200x200',
    brand: 't&K',
    shipping: {
      weight: '0.65',
      size: 'medium',
    },
    lastUpdated: 'Wed Jul 11 2018 08:59:47 GMT+0000 (UTC)',
    tags: ['seasonal', 'funny'],
  },
  {
    _id: '5ba93a6d429b51c1baa068a1',
    name: 'Manning',
    disc:
      'Sint proident magna eu nostrud nulla proident tempor voluptate magna ullamco quis id.',
    category: 'food',
    available: false,
    instock: 6,
    price: '26.69',
    picture: 'http://placehold.it/200x200',
    brand: 'bento',
    shipping: {
      weight: '1.78',
      size: 'large',
    },
    lastUpdated: 'Mon Dec 14 2015 08:45:24 GMT+0000 (UTC)',
    tags: ['colorful', 'seasonal'],
  },
  {
    _id: '5ba93a6d465013117627a5c3',
    name: 'Frederick',
    disc: 'Id officia ipsum excepteur laborum cupidatat nulla do irure.',
    category: 'christmas',
    available: true,
    instock: 6,
    price: '36.33',
    picture: 'http://placehold.it/200x200',
    brand: 'bento',
    shipping: {
      weight: '0.56',
      size: 'large',
    },
    lastUpdated: 'Wed Sep 30 2015 00:09:12 GMT+0000 (UTC)',
    tags: ['colorful', 'colorful'],
  },
];

module.exports = seed;
